server:
  port: 666

inputXmlPath: profile-management/src/main/resources/xml/input/employees-input.xml

nodes:
  - type: XSLT
    properties:
      xsltPath: profile-management/src/main/resources/xslt/xerris-transformer.xslt
      another: aaa
  - type: XSLT
    properties:
      xsltPath: profile-management/src/main/resources/xslt/xerris-location-transformer.xslt
      another: bbbb
  - type: XPATH
    properties:
      xpathExpression: xerris/location/vancouver/name
