inputPath: src/main/resources/xml/input/employees-input.xml

nodes:
  - type: XSLT
    properties:
      xsltPath: src/main/resources/xslt/xerris-transformer.xslt
      another: ass
  - type: XSLT
    properties:
      xsltPath: src/main/resources/xslt/xerris-location-transformer.xslt
      another: bbbb
